### ISSUE TITLE
Adding CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by kailashchoudhary11** [Lightning-AI-Dev/Awesome-Lightning#15]
code of conduct is an important part of documentation and I think it must be included!

**Comment by aniketmaurya** [comment]
hi @kailashchoudhary11, we already have it present [here](https://github.com/Lightning-AI-Dev/Awesome-Lightning/blob/main/.github/CODE_OF_CONDUCT.md).

There are a few other contributing ideas [here](https://github.com/Lightning-AI-Dev/Awesome-Lightning/issues/5).

Thank you 😄
